# Generated by Django 4.2.7 on 2023-11-17 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0014_profile_education_profile_profession"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="first_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="last_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
