# Generated by Django 4.0 on 2023-10-25 13:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_article_likes_article_unlikes_delete_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='unlikes',
        ),
        migrations.AlterField(
            model_name='article',
            name='likes',
            field=models.ManyToManyField(related_name='liked_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
